### ISSUE TITLE
Remnote remote controller

### ISSUE THREAD

**Issue by z4151** [remnoteio/remnote-gamepad#2]
### Did you update to the latest plugin version?

- [X] Updated RemNote

### RemNote app version

DEsktop

### Plugin version

Latest

### What happened?

I have two controller and two computers (laptop and a desktop). The controller-laptop combo works great! The controller-desktop combo isn't working. I tested that the controller itself is working fine on my desktop, but when I go on remnote it doesn't do anything

### Code of Conduct

- [X] I agree

**Comment by coldenate** [comment]
Hi! Are the two computers using the same operating system? Can you send some info about your desktop? 

Also, please enable debug mode in the plugin's settings. Then, make some attempts to use it in the Queue. Once done, please send me the console output in the dev tools!
